name: Preview

on:
  push:
    branches-ignore: [main]
    paths:
      - "rules.typ"
      - "template.typ"

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: P1DT12H
          purge-primary-key: never

      - name: Enter Nix devShell, compile (output ASCII name)
        run: |
          nix develop --command bash -lc '
            set -euo pipefail
            typst compile rules.typ "omu-aikido_rules.pdf"
          '

      - name: Create date tag
        id: create_tag
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TAG="$(date -u +%Y-%m-%d)"
          if git ls-remote --tags origin "refs/tags/${TAG}" | grep -q "${TAG}"; then
            TAG="${TAG}.v${GITHUB_RUN_NUMBER}"
          fi

          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Upload
        run: |
          set -euxo pipefail
          TAG=${{ steps.create_tag.outputs.tag }}
          gh release create "$TAG" --generate-notes --prerelease --title "Preview $TAG" omu-aikido_rules.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
